[package]
name = "autograph"
version = "0.0.4"
authors = ["Charles R Earp <charles.r.earp@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "Deep Neural Network Library for Rust"
homepage = "https://github.com/charles-r-earp/autograph"
repository = "https://github.com/charles-r-earp/autograph"
keywords = ["neural-networks", "machine-learning", "cuda", "deep-learning", "autograd"]
categories = ["science"]
readme = "README.md"
publish = false

[dependencies]
wgpu = "0.6.0"
proxy-enum = "0.3.0"
bytemuck = "1.4.1"
ndarray = "0.14.0"
smol = "1.2.5"
dashmap = "3.11.10"
rspirv = "0.7.0"
serde = { version = "1.0.118", features = ["derive"] }
ahash = "0.6.1"
glsl-to-spirv = "0.1.7"



