[package]
name = "autograph"
version = "0.0.4"
authors = ["Charles R Earp <charles.r.earp@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "Deep Neural Network Library for Rust"
homepage = "https://github.com/charles-r-earp/autograph"
repository = "https://github.com/charles-r-earp/autograph"
keywords = ["neural-networks", "machine-learning", "cuda", "deep-learning", "autograd"]
categories = ["science"]
readme = "README.md"
publish = false

[dependencies]
wgpu = "0.6.0"
proxy-enum = "0.3.0"
async-std = { version = "1.7.0", features = ["attributes", "unstable"] }
evmap = "10.0.2"
evmap-derive = "0.2.0"
bytemuck = "1.4.1"



